require: rubocop-rails

AllCops:
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - '**/*.rb'
    - '**/*.jbuilder'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - db/schema.rb

Metrics/LineLength:
  Max: 110

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
