name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432/tcp
            # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Install PostgreSQL client
      run: sudo apt-get install libpq-dev # required to compile pg ruby gem

    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Create Database
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        RAILS_ENV: test
      run: |
        bin/rails db:setup

    - name: Rubocop
      run: |
        bundle exec rubocop

    - name: Test
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
      run: |
        bundle exec rake
